/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package velhos_registos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rodolfo
 */
public class Cadastro_interface extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_interface
     */
    public Cadastro_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Cod_aluno_Label = new javax.swing.JLabel();
        Cod_Aluno_JTexField = new javax.swing.JTextField();
        Senha_Aluno_Label = new javax.swing.JLabel();
        Senha_Aluno_JTexField = new javax.swing.JTextField();
        Nome_Aluno_Label = new javax.swing.JLabel();
        Nome_Aluno_JTexField = new javax.swing.JTextField();
        Atestado_Aluno_Label = new javax.swing.JLabel();
        Atestado_Aluno_JTexField = new javax.swing.JTextField();
        Fixa_Med_Label = new javax.swing.JLabel();
        Fixa_Med_Aluno_JTexField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Btn_Cadastar_Ok = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cod_aluno_Label.setText("Login:");

        Senha_Aluno_Label.setText("Senha:");

        Senha_Aluno_JTexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Senha_Aluno_JTexFieldActionPerformed(evt);
            }
        });

        Nome_Aluno_Label.setText("Nome:");

        Atestado_Aluno_Label.setText("Atestado:");

        Fixa_Med_Label.setText("Fixa Médica:");

        jLabel6.setText("Bem vindo novo aluno");

        Btn_Cadastar_Ok.setText("Cadastrar !");
        Btn_Cadastar_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cadastar_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Fixa_Med_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Atestado_Aluno_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nome_Aluno_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Senha_Aluno_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cod_aluno_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fixa_Med_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Senha_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cod_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nome_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Atestado_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(Btn_Cadastar_Ok)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cod_aluno_Label)
                    .addComponent(Cod_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha_Aluno_Label)
                    .addComponent(Senha_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome_Aluno_Label)
                    .addComponent(Nome_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atestado_Aluno_Label)
                    .addComponent(Atestado_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fixa_Med_Label)
                    .addComponent(Fixa_Med_Aluno_JTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Cadastar_Ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Senha_Aluno_JTexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Senha_Aluno_JTexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Senha_Aluno_JTexFieldActionPerformed

    private void Btn_Cadastar_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cadastar_OkActionPerformed
        // TODO add your handling code here:
        String cod_aluno = Cod_Aluno_JTexField.getText().toString();
        System.out.println(cod_aluno);
        String senha = Senha_Aluno_JTexField.getText().toString();
        String nome = Nome_Aluno_JTexField.getText();
        int num_faltas = 0;
        String atestado = Atestado_Aluno_JTexField.getText();
        String fixa_med = Fixa_Med_Aluno_JTexField.getText();
        
        Cadastro cadastro_aluno = new Cadastro();
        try {
            cadastro_aluno.Cadastrar_Aluno(
                    Integer.parseInt(cod_aluno),
                    Integer.parseInt(senha),
                    nome,
                    num_faltas,
                    atestado,
                    fixa_med
            );
            JOptionPane.showMessageDialog(rootPane,"OK");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "o Cadastro deu errado!!");
        }
    }//GEN-LAST:event_Btn_Cadastar_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Atestado_Aluno_JTexField;
    private javax.swing.JLabel Atestado_Aluno_Label;
    private javax.swing.JButton Btn_Cadastar_Ok;
    private javax.swing.JTextField Cod_Aluno_JTexField;
    private javax.swing.JLabel Cod_aluno_Label;
    private javax.swing.JTextField Fixa_Med_Aluno_JTexField;
    private javax.swing.JLabel Fixa_Med_Label;
    private javax.swing.JTextField Nome_Aluno_JTexField;
    private javax.swing.JLabel Nome_Aluno_Label;
    private javax.swing.JTextField Senha_Aluno_JTexField;
    private javax.swing.JLabel Senha_Aluno_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
