/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Objetos_Conexao.Cadastro;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author denise
 */
public class Cadastro_turma extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_turma
     */
    public Cadastro_turma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Lbl_cod = new javax.swing.JLabel();
        Lbl_numAluno = new javax.swing.JLabel();
        Lbl_horarios = new javax.swing.JLabel();
        Lbl_aluno = new javax.swing.JLabel();
        Lbl_prof = new javax.swing.JLabel();
        Text_cod = new javax.swing.JTextField();
        Text_numAlunos = new javax.swing.JTextField();
        Text_horarios = new javax.swing.JTextField();
        Text_alunos = new javax.swing.JTextField();
        Text_prof = new javax.swing.JTextField();
        Btn_voltar = new javax.swing.JButton();
        Btn_cancel = new javax.swing.JButton();
        Btn_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_titulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Lbl_titulo.setText("Cadastrar turma");

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        Lbl_cod.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_cod.setText("Código da turma:");

        Lbl_numAluno.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_numAluno.setText("Quantidade de aluno:");

        Lbl_horarios.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_horarios.setText("Horários:");

        Lbl_aluno.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_aluno.setText("Alunos:");

        Lbl_prof.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_prof.setText("Professor:");

        Text_cod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Text_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_codActionPerformed(evt);
            }
        });

        Text_numAlunos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        Text_horarios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        Text_alunos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        Text_prof.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        Btn_voltar.setBackground(new java.awt.Color(221, 226, 242));
        Btn_voltar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_voltar.setText("Voltar");
        Btn_voltar.setToolTipText("");
        Btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_voltar.setPreferredSize(new java.awt.Dimension(100, 35));
        Btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_voltarActionPerformed(evt);
            }
        });

        Btn_cancel.setBackground(new java.awt.Color(221, 226, 242));
        Btn_cancel.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_cancel.setText("Cancelar");
        Btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_cancel.setPreferredSize(new java.awt.Dimension(100, 35));
        Btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cancelActionPerformed(evt);
            }
        });

        Btn_ok.setBackground(new java.awt.Color(221, 226, 242));
        Btn_ok.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_ok.setText("Confirmar");
        Btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_ok.setPreferredSize(new java.awt.Dimension(100, 35));
        Btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_cod)
                            .addComponent(Lbl_numAluno)
                            .addComponent(Lbl_horarios)
                            .addComponent(Lbl_aluno)
                            .addComponent(Lbl_prof))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_cod)
                            .addComponent(Text_horarios)
                            .addComponent(Text_numAlunos)
                            .addComponent(Text_alunos)
                            .addComponent(Text_prof, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_cod)
                    .addComponent(Text_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_numAluno)
                    .addComponent(Text_numAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_horarios)
                    .addComponent(Text_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_aluno)
                    .addComponent(Text_alunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_prof)
                    .addComponent(Text_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(Lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Lbl_titulo)
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_codActionPerformed

    private void Btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_voltarActionPerformed
        pg_inicial_professor cancel = new pg_inicial_professor();
        cancel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Btn_voltarActionPerformed

    private void Btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cancelActionPerformed
        Text_cod.setText(null);
        Text_numAlunos.setText(null);
        Text_alunos.setText(null);
        Text_prof.setText(null);
        Text_horarios.setText(null);
    }//GEN-LAST:event_Btn_cancelActionPerformed

    private void Btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_okActionPerformed
        String cod = Text_cod.getText();
        String numAlunos = Text_numAlunos.getText();
        String aluno = Text_alunos.getText();
        String prof = Text_prof.getText();
        String horarios = Text_horarios.getText();
        
        Cadastro cadastrarTurma = new Cadastro();
        try {
            cadastrarTurma.Cadastrar_turma(
                    Integer.parseInt(cod),
                    Integer.parseInt(numAlunos),
                    Integer.parseInt(horarios),
                    Integer.parseInt(aluno),
                    Integer.parseInt(prof)
            );
            JOptionPane.showMessageDialog(this, "Cadastro efetuado com sucesso!", 
                    "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "O cadastro da turma deu errado!",
            "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_Btn_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_turma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cancel;
    private javax.swing.JButton Btn_ok;
    private javax.swing.JButton Btn_voltar;
    private javax.swing.JLabel Lbl_aluno;
    private javax.swing.JLabel Lbl_cod;
    private javax.swing.JLabel Lbl_horarios;
    private javax.swing.JLabel Lbl_numAluno;
    private javax.swing.JLabel Lbl_prof;
    private javax.swing.JLabel Lbl_titulo;
    private javax.swing.JTextField Text_alunos;
    private javax.swing.JTextField Text_cod;
    private javax.swing.JTextField Text_horarios;
    private javax.swing.JTextField Text_numAlunos;
    private javax.swing.JTextField Text_prof;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
