/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Objetos_Conexao.Login;
import Objetos_Entidades.Professor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author denise
 */
public class Login_professor extends javax.swing.JFrame {

    /**
     * Creates new form Login_porfessor
     */
    public Login_professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_login = new javax.swing.JLabel();
        Lbl_senha = new javax.swing.JLabel();
        Text_login = new javax.swing.JTextField();
        Text_senha = new javax.swing.JTextField();
        Btn_entrar = new javax.swing.JButton();
        Btn_cadastrar = new javax.swing.JButton();
        Btn_voltar = new javax.swing.JButton();
        Lbl_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login professor");
        setPreferredSize(new java.awt.Dimension(390, 379));

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        Lbl_login.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_login.setText("Login:");

        Lbl_senha.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_senha.setText("Senha:");

        Text_login.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        Text_senha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        Btn_entrar.setBackground(new java.awt.Color(236, 236, 236));
        Btn_entrar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_entrar.setText("Entrar");
        Btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_entrar.setPreferredSize(new java.awt.Dimension(100, 35));
        Btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_entrarActionPerformed(evt);
            }
        });

        Btn_cadastrar.setBackground(new java.awt.Color(236, 236, 236));
        Btn_cadastrar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_cadastrar.setText("Cadastrar");
        Btn_cadastrar.setToolTipText("Cadastrar novo professor");
        Btn_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_cadastrar.setPreferredSize(new java.awt.Dimension(100, 35));
        Btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cadastrarActionPerformed(evt);
            }
        });

        Btn_voltar.setBackground(new java.awt.Color(236, 236, 236));
        Btn_voltar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_voltar.setText("Voltar");
        Btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_voltar.setMaximumSize(new java.awt.Dimension(78, 37));
        Btn_voltar.setPreferredSize(new java.awt.Dimension(100, 35));
        Btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_login)
                            .addComponent(Lbl_senha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(Text_login)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_login)
                    .addComponent(Text_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_senha)
                    .addComponent(Text_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(Btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Lbl_titulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Lbl_titulo.setText("Bem Vindo Professor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Lbl_titulo)
                .addContainerGap(94, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Lbl_titulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cadastrarActionPerformed
        Cadastro_Professor prof = new Cadastro_Professor();
        prof.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Btn_cadastrarActionPerformed
    
    pg_inicial_professor pg_prof;
    
    private void Btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_entrarActionPerformed
        String login = Text_login.getText();
        String senha = Text_senha.getText();
        
        ArrayList<Professor> prof = new ArrayList();
        Login listar = new Login();
        
        try {
            prof = listar.loginProfessores(login, senha);
            
            int cod = prof.get(0).getCod_prof();
            String nome = prof.get(0).getNome();
            String atividade= prof.get(0).getAtiv_ministrada();
            int ch = prof.get(0).getCarga_horaria();
            
            pg_prof = new pg_inicial_professor();
            pg_prof.setVisible(true);
            pg_prof.ReceberDados(cod, nome, atividade, ch);
            
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_professor.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this, "Login e/ou senha incorretos", "Erro no login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_entrarActionPerformed

    private void Btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_voltarActionPerformed
        TelaEscolhaLogin cancel =  new TelaEscolhaLogin();
        cancel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cadastrar;
    private javax.swing.JButton Btn_entrar;
    private javax.swing.JButton Btn_voltar;
    private javax.swing.JLabel Lbl_login;
    private javax.swing.JLabel Lbl_senha;
    private javax.swing.JLabel Lbl_titulo;
    private javax.swing.JTextField Text_login;
    private javax.swing.JTextField Text_senha;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
