/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Objetos_Conexao.Login;
import Objetos_Entidades.Coordenador;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author denise
 */
public class pg_inicial_coordenador extends javax.swing.JFrame {

    /**
     * Creates new form pg_inicial_coordenador
     */
    public pg_inicial_coordenador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_alterar = new javax.swing.JButton();
        Btn_sair = new javax.swing.JButton();
        Lbl_turma = new javax.swing.JLabel();
        Lbl_cod = new javax.swing.JLabel();
        Lbl_valor_turma = new javax.swing.JLabel();
        Lbl_valor_cod = new javax.swing.JLabel();
        Lbl_nome = new javax.swing.JLabel();
        Lbl_valor_nome = new javax.swing.JLabel();
        Btn_rmProf = new javax.swing.JButton();
        Btn_faltas = new javax.swing.JButton();
        Btn_rmAluno = new javax.swing.JButton();
        Lbl_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do usuário");

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        Btn_alterar.setBackground(new java.awt.Color(221, 226, 242));
        Btn_alterar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_alterar.setText("Alterar dados");
        Btn_alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_alterar.setPreferredSize(new java.awt.Dimension(130, 35));
        Btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_alterarActionPerformed(evt);
            }
        });

        Btn_sair.setBackground(new java.awt.Color(221, 226, 242));
        Btn_sair.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_sair.setText("Sair");
        Btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_sair.setPreferredSize(new java.awt.Dimension(130, 35));
        Btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sairActionPerformed(evt);
            }
        });

        Lbl_turma.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_turma.setText("Turma:");

        Lbl_cod.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_cod.setText("Código de coord.:");
        Lbl_cod.setToolTipText("");

        Lbl_valor_turma.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Lbl_valor_turma.setPreferredSize(new java.awt.Dimension(163, 27));

        Lbl_valor_cod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Lbl_valor_cod.setPreferredSize(new java.awt.Dimension(163, 27));

        Lbl_nome.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_nome.setText("Nome:");

        Lbl_valor_nome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Lbl_valor_nome.setPreferredSize(new java.awt.Dimension(163, 27));

        Btn_rmProf.setBackground(new java.awt.Color(221, 226, 242));
        Btn_rmProf.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_rmProf.setText("Remover professor");
        Btn_rmProf.setToolTipText("");
        Btn_rmProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_rmProf.setPreferredSize(new java.awt.Dimension(130, 35));
        Btn_rmProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_rmProfActionPerformed(evt);
            }
        });

        Btn_faltas.setBackground(new java.awt.Color(221, 226, 242));
        Btn_faltas.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_faltas.setText("Atribuir faltas");
        Btn_faltas.setToolTipText("");
        Btn_faltas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_faltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_faltasActionPerformed(evt);
            }
        });

        Btn_rmAluno.setBackground(new java.awt.Color(221, 226, 242));
        Btn_rmAluno.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_rmAluno.setText("Remover aluno");
        Btn_rmAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_rmAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_rmAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_rmProf, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(Btn_rmAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_faltas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(Btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_cod)
                            .addComponent(Lbl_turma)
                            .addComponent(Lbl_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_valor_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(Lbl_valor_cod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_valor_turma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_valor_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_cod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_valor_cod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_turma)
                    .addComponent(Lbl_valor_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_rmAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_rmProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_faltas))
                .addGap(18, 18, 18)
                .addComponent(Btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        Lbl_titulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Lbl_titulo.setText("Seja bem vindo coordenador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Lbl_titulo)
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_alterarActionPerformed
        Atualizar_coordenador atualiza = new Atualizar_coordenador();
        atualiza.setVisible(true);
       // this.setVisible(false);
    }//GEN-LAST:event_Btn_alterarActionPerformed

    private void Btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sairActionPerformed
        TelaEscolhaLogin voltar = new TelaEscolhaLogin();
        voltar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_sairActionPerformed

    private void Btn_rmProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_rmProfActionPerformed
        RemoverProf rmProf = new RemoverProf();
        rmProf.setVisible(true);
    }//GEN-LAST:event_Btn_rmProfActionPerformed

    private void Btn_faltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_faltasActionPerformed
        FazerFrequencia f = new FazerFrequencia();
        f.setVisible(true);
    }//GEN-LAST:event_Btn_faltasActionPerformed

    private void Btn_rmAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_rmAlunoActionPerformed
        RemoverAluno rmAluno = new RemoverAluno();
        rmAluno.setVisible(true);
    }//GEN-LAST:event_Btn_rmAlunoActionPerformed

    public ArrayList<Coordenador> ReceberDados(int login, int senha)throws SQLException{
      ArrayList<Coordenador> lista = new ArrayList();
      Login novo = new Login();
      lista = novo.loginCoordenadores(Integer.toString(login), Integer.toString(senha));
      Lbl_valor_cod.setText(Integer.toString(lista.get(0).getCod_coordenador()));
      Lbl_valor_nome.setText(lista.get(0).getNome());
      Lbl_valor_turma.setText(Integer.toString(lista.get(0).getCod_turma()));
      return lista;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pg_inicial_coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pg_inicial_coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pg_inicial_coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pg_inicial_coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pg_inicial_coordenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_alterar;
    private javax.swing.JButton Btn_faltas;
    private javax.swing.JButton Btn_rmAluno;
    private javax.swing.JButton Btn_rmProf;
    private javax.swing.JButton Btn_sair;
    private javax.swing.JLabel Lbl_cod;
    private javax.swing.JLabel Lbl_nome;
    private javax.swing.JLabel Lbl_titulo;
    private javax.swing.JLabel Lbl_turma;
    private javax.swing.JLabel Lbl_valor_cod;
    private javax.swing.JLabel Lbl_valor_nome;
    private javax.swing.JLabel Lbl_valor_turma;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
