/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JFrame;

/**
 *
 * @author denise
 */
public class TelaEscolhaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaEscolhaLogin
     */
    public TelaEscolhaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Lbl_subtitulo = new javax.swing.JLabel();
        Btn_aluno = new javax.swing.JButton();
        Btn_professor = new javax.swing.JButton();
        Btn_coordenador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicação para armazenar registros do ACORDI");
        setBackground(new java.awt.Color(199, 108, 17));

        Lbl_titulo.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        Lbl_titulo.setText("Bem Vindo!");

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        Lbl_subtitulo.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Lbl_subtitulo.setText("Escolha uma das opções de login abaixo:");

        Btn_aluno.setBackground(new java.awt.Color(221, 226, 242));
        Btn_aluno.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_aluno.setText("Aluno");
        Btn_aluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_alunoActionPerformed(evt);
            }
        });

        Btn_professor.setBackground(new java.awt.Color(221, 226, 242));
        Btn_professor.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_professor.setText("Professor");
        Btn_professor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_professorActionPerformed(evt);
            }
        });

        Btn_coordenador.setBackground(new java.awt.Color(221, 226, 242));
        Btn_coordenador.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        Btn_coordenador.setText("Coordenador");
        Btn_coordenador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_coordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_coordenadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Lbl_subtitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Btn_coordenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_professor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Lbl_subtitulo)
                .addGap(18, 18, 18)
                .addComponent(Btn_aluno)
                .addGap(18, 18, 18)
                .addComponent(Btn_professor)
                .addGap(18, 18, 18)
                .addComponent(Btn_coordenador)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_alunoActionPerformed
        Login_aluno aluno = new Login_aluno();
        aluno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_alunoActionPerformed

    private void Btn_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_professorActionPerformed
        this.dispose();
        Login_professor prof = new Login_professor();
        prof.setVisible(true);
    }//GEN-LAST:event_Btn_professorActionPerformed

    private void Btn_coordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_coordenadorActionPerformed
        this.dispose();
        Login_coordenador coordenador = new Login_coordenador();
        coordenador.setVisible(true);
    }//GEN-LAST:event_Btn_coordenadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscolhaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_aluno;
    private javax.swing.JButton Btn_coordenador;
    private javax.swing.JButton Btn_professor;
    private javax.swing.JLabel Lbl_subtitulo;
    private javax.swing.JLabel Lbl_titulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
